export const LANGUAGE_EXTENSIONS = {
  java: '.java',
  mongodb: '.js',
  python: '.py',
  javascript: '.js',
  typescript: '.ts',
  jsx: '.jsx',
  tsx: '.tsx',
  html: '.html',
  css: '.css',
  scss: '.scss',
  c: '.c',
  cpp: '.cpp',
  cs: '.cs',
  go: '.go',
  rust: '.rs',
  php: '.php',
  ruby: '.rb',
  kotlin: '.kt',
  swift: '.swift',
  sql: '.sql',
  json: '.json',
  markdown: '.md',
  shell: '.sh',
  bash: '.sh'
};
